# Generated by Django 5.0.4 on 2024-05-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BLOG", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="name",
            field=models.CharField(max_length=70, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="product/photo", verbose_name="Фото"
            ),
        ),
    ]
