# Generated by Django 5.0.4 on 2024-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BLOG", "0002_alter_blog_description_alter_blog_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/photo", verbose_name="Фото"
            ),
        ),
    ]
