# Generated by Django 5.0.4 on 2024-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "created_at", "updated_at"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="date_add",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="date_last",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата производства продукта"
            ),
        ),
    ]
