# Generated by Django 5.0.4 on 2024-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото",
                null=True,
                upload_to="product/photo",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(help_text="Введите описание", verbose_name="Цена"),
        ),
    ]
