# Generated by Django 5.0.4 on 2024-05-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_photo_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="viewed",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
